version: 1
services:
  app:
    runtime: python3.8
    build:
      source: .
      dockerfile: Dockerfile
    command: ["gunicorn", "app:app", "-w", "4", "-k", "uvicorn.workers.UvicornWorker"]
    port: 8080
    healthcheck:
      command: ["curl", "-f", "http://localhost:8080/health"]
      interval: 5s
      timeout: 2s
      retries: 3
      start_period: 10s
