version: 1
services:
  - name: my-python-app
    source:
      type: git
      repository: https://github.com/omkarpatel00/my-python-app.git
      subdirectory: my-python-app
    build:
      command: pip install -r requirements.txt
      runtime: python3.9
    start:
      command: python app.py
